update: files (structure) / add: header component
cetav-ddw/proxy-fe pull request #10
Opened 2019-10-19 18:42 UTC by JgeovanniAm

2019-10-19 18:45 UTC, NycollSM approved these changes
code review hecho.

2019-10-19 22:07 UTC, jleiva commented on src/components/sections/herobanner/HeroBanner.jsx
> +  // la ruta del video va cambair dependiendo en que página me encuentre
talvez es mas facil pasarle la ruta del video como un prop

2019-10-19 23:45 UTC, jleiva requested changes

2019-10-19 23:45 UTC, jleiva commented on src/components/sections/dateheader/date.scss
> +@import '../../../scss/styles.scss';
revisar que siga los estandares de CSS

Ademas, creo que tienen que modificar styles.css, porque los componentes de Scss solo deberian de importar las variables, y segun veo, styles.scss importa variables, default y keyframes

2019-10-19 23:45 UTC, jleiva commented on src/components/layouts/header.jsx
> +import DateHeader from '../sections/dateheader/DateHeader';
un toque paara que los import no se vean tan feillos es tener un index.jsx dentro de cada folder, y se usa como nombre del componente el nombre del folder. Es lo que indican en la parte de Component Naming en https://github.com/airbnb/javascript/tree/master/react#naming

2019-10-19 23:45 UTC, jleiva commented on src/components/layouts/header.jsx
> +import React from 'react';
header es un section, layout esta pensado para que lo usen los pages, en caso de que cada page tenga un layout diferente

2019-10-19 23:45 UTC, jleiva commented on src/components/layouts/header.jsx
> +import './layout.scss';
header no deberia de importar layout.scss, deberia de importar algo como header.scss

2019-10-19 23:45 UTC, jleiva commented on src/components/sections/dateheader/DateHeader.jsx
> +    <Paragraph className="wrapper-animation__item" inner="replace-image" />
Porque estas pasando replace-image, si eso es el texto dentro del p?

La otra cosa, este tipo de componentes seria mejor que reciban el contenido como children, tipo:

`<Paragraph props="">Aqui va el texto, iconos o lo que sea</Paragraph>`

Lo anterior implica modificar el componente Paragraph.jsx para que reciba children y no inner como prop

2019-10-20 00:16 UTC, JgeovanniAm commented on src/components/layouts/header.jsx
> +import React from 'react';
pero no es que sections es un conjunto de units y layout es un conjunto de sections y units

 <header class="header">
    <div class="wrapper-animation">
      <p class="wrapper-animation__item">replace-image</p>
      <p class="wrapper-animation__item">replace-image</p>
      <p class="wrapper-animation__item">replace-image</p>
    </div>
    <div class="herobanner">
      <video class="herobanner__video" poster="./img/bg-footer-h.jpg" autoplay muted loop>
        <source src="./mp4/main.mp4" type="video/mp4">
      </video>
      <button class="btn-nav" id="open">
        <span class="btn-nav__text">Menú</span>
        <span class="circle-animation">
          <svg class="btn-nav__svg " height="60" width="60">
            <circle class="progress-inner" cx="35" cy="35" r="13" stroke-width="4" fill="none" stroke="#16E024" />
          </svg>
        </span>
      </button>
    </div>
    <div class="wrapper-nav">
      <ul class="nav-list">
        <li class="nav-list__item">
          <a href="./index.html" class="nav-list__link">Inicio</a>
        </li>
        <li class="nav-list__item">
          <a href="proxy.html" class="nav-list__link">Proxy</a>
        </li>
        <li class="nav-list__item">
          <a href="./sinestesia.html" class="nav-list__link">Sinestesia</a>
        </li>
        <li class="nav-list__item">
          <a href="./pabellon.html" class="nav-list__link">Pabellón</a>
        </li>
      </ul>
    </div>
  </header>

2019-10-20 00:25 UTC, JgeovanniAm commented on src/components/layouts/header.jsx
> +import React from 'react';
sería bueno un ejemplo porqué ahorita estoy confundido

2019-10-20 01:22 UTC, jleiva commented on src/components/layouts/header.jsx
> +import React from 'react';
Ojo https://reactjs.org/docs/composition-vs-inheritance.html#containment

Lo que va en el folder de Layout son componentes que lo unico que tienen es la distribucion de un page. Por ejemplo:

Puedo tener un componente que se llame DefaultLayout.jsx, lo que tiene por dentro es:

```
<div className="">
  <div>
    {full}
  </div>
  <div>
    {lefSide}
  </div>
  <div>
    {rightSide}
  </div>
</div>
```

2019-10-20 02:45 UTC, jleiva requested changes

2019-10-20 02:45 UTC, jleiva commented on src/components/sections/nav/Nav.jsx
> +        <Link to="./sinestesia" className="nav-list__link">Sinestesia</Link>
el ./ creo que no se necesita

2019-10-20 02:45 UTC, jleiva commented on src/components/layouts/header.jsx
> +    const { activeNav } = this.state;
podes hacer uno solo para el state, {activeNav, pathVideo } asi no repetis en linea 35

2019-10-20 02:51 UTC, jleiva requested changes

2019-10-20 02:51 UTC, jleiva commented on src/components/layouts/header.jsx
> +  componentDidMount() {
toda esta logica se puede simplificar con solo pasar el pathVideo como un prop desde el page, algo como

```
const Obras = () => (
  <>
    <SEO title={titlePage} />
    <Header pageName={titlePage} videoSrc="el fucking video" />
  </>
);
```

2019-10-20 02:51 UTC, jleiva commented on src/components/layouts/header.jsx
> +          pageName === 'obras' || pageName === 'proxy'
una mejor solucion es no repetir los componentes, por ejemplo, sea true o false siempre vas a necesitar Dateheader, BtnNav y Nav, incluso con los mismos props, entonces, la condicion deberia de ser para saver si se necesita, o no, HeroBanner

2019-10-20 02:51 UTC, jleiva commented on src/components/layouts/header.jsx
> +  activeBntNav() {
talvez lo mejor seria que solo Nav sepa cuando se tiene, o no, que abrir. Este medodo y el estado asociado son como especificos de la navegacion. Podriamos tener un solo componente Nav, que incluya el boton y el menu

2019-10-20 03:00 UTC, jleiva requested changes

2019-10-20 03:00 UTC, jleiva commented on src/components/sections/dateheader/DateHeader.jsx
> +const DateHeader = () => (
Talvez algo como EventDate es mejor

2019-10-20 03:00 UTC, jleiva commented on src/components/sections/nav/Nav.jsx
> +const Nav = ({ toggleNav }) => (
aqui puede estar el boton, navbtn/Btn.jsx, asi el saber si esta abierto/cerrado se maneja todo desde aca

2019-10-20 15:40 UTC, jleiva requested changes

2019-10-20 15:40 UTC, jleiva commented on src/components/layouts/MainLayout.jsx
> +const Header = ({ head, sections, allies }) => (
ojo, la const debe ser MainLayout. Si el contenido de footer no cambia, aqui solo deberias de usar el componente, y dentro de Footer incluir allies, no pasarlo como prop

2019-10-20 15:40 UTC, jleiva commented on src/pages/index.jsx
> +      allies={
en todos los pages estas enviando allies, y eso es para fooyter, como te puse antes, mejor que eso sea parte de Footer y no del layout

2019-10-20 15:40 UTC, jleiva commented on src/pages/index.jsx
> +            <EventData />
en todos los pages estas pasando EventData y Nav, eso puede estar dentro de Header, porque siempre se usan, y solo pasar un prop que se use para saber cuando usar o no HeroBanner

2019-10-20 15:40 UTC, jleiva commented on src/components/sections/eventDate/EventDate.jsx
> +    <Paragraph variant="wrapper-animation__item">replace-img </Paragraph>
porque usar replace-img como texto, si aqui va la fecha

2019-10-20 18:54 UTC, JgeovanniAm commented on src/pages/index.jsx
> +            <EventData />
ok en sections hago un componente que se llame header.jsx y utilize herobanner eventDate y Nav? no es mejor que eso quede separado?

2019-10-20 18:57 UTC, JgeovanniAm commented on src/pages/index.jsx
> +            <EventData />
como hacer otra carpeta de compoentes como header y footer que solo esperen que se armen de componentes pequeños?

2019-10-21 15:38 UTC, glorianaa80 reviewed
code review listo!

2019-10-21 17:05 UTC, jleiva commented on src/components/layouts/MainLayout.jsx
> +    {head}
```
<Header videoOpt={opts} />
<div className="top">{top}</div>
<div className="left">{left}</div>
<div className="right">{right}</div>
<Footer />
```

2019-10-21 21:01 UTC, jleiva requested changes

2019-10-21 21:01 UTC, jleiva commented on src/components/layouts/MainLayout.jsx
> +  videoOpt: false,
segun propTypes videoOpt es un string, aqui lo tenes como boolean; ademas debe el nombre esta mal, aqui es MainLayout y estas usando Header

2019-10-21 21:01 UTC, jleiva commented on src/components/units/Button.jsx
> +    onClick={() => handleClickbtn()}
el componente solo debe recibir el prop `onClick={handleClickbtn}>`, no hace falta declararlo como una funcion

2019-10-21 21:05 UTC, JgeovanniAm commented on src/components/layouts/MainLayout.jsx
> +  videoOpt: false,
Como default lo pongo como null? O string vacío?

2019-10-21 21:15 UTC, jleiva commented on src/components/layouts/MainLayout.jsx
> +  videoOpt: false,
me refiero a la linea 26, tenes Header.propTypes, y deberia de ser MainLayout.propTypes

Debe ser un string vacio

2019-10-21 22:35 UTC, merged