Socialmedia
cetav-ddw/proxy-fe pull request #13
Opened 2019-10-23 01:00 UTC by NycollSM

Agrego seccion de redes sociales en paginas

2019-10-23 03:44 UTC, jleiva requested changes

2019-10-23 03:44 UTC, jleiva commented on src/pages/index.jsx
> +        <SocialMedia />
si esto de SocialMedia va en todas las paginas en el mismo lugar, entonces mejor incluirlo desde MainLayout

2019-10-23 03:44 UTC, jleiva commented on src/components/sections/social-media/social.scss
> +@import '../../../scss/settings/vars.scss';
los selectores tienen que estar ordenados alfabeticamente, verifica que el file cumple con la guia de estandares

2019-10-23 17:49 UTC, jleiva requested changes

2019-10-23 17:49 UTC, jleiva commented on src/components/sections/social-media/social.scss
> +@import '../../../scss/settings/vars.scss';
@NycollSM no aplicaste esto

2019-10-24 15:32 UTC, glorianaa80 reviewed
code review listo

2019-10-25 15:19 UTC, merged