Boton
cetav-ddw/proxy-fe pull request #38
Opened 2019-10-29 21:58 UTC by NycollSM

Boton para ver todas las obras

2019-10-29 22:01 UTC, glorianaa80 approved these changes
Code review listo

2019-10-29 22:01 UTC, JgeovanniAm reviewed
listo

2019-10-29 22:06 UTC, jleiva requested changes

2019-10-29 22:06 UTC, jleiva commented on src/pages/index.jsx
> +            <BtnObras />
no hace falta que sea un componente

2019-10-29 22:31 UTC, glorianaa80 approved these changes
listo

2019-10-29 22:36 UTC, jleiva requested changes

2019-10-29 22:36 UTC, jleiva commented on src/pages/index.jsx
> +import { format } from 'util';
que es esto de formar? donde se usa?

2019-10-29 22:36 UTC, jleiva commented on src/pages/index.jsx
> +              <span>Ver todas las Obras</span>
ponele una clase al span, porfa, la idea de BEM es mantener la especificidad lo mas plana posible y y evitar anidacion

2019-10-30 02:40 UTC, jleiva approved these changes

2019-10-30 02:40 UTC, merged