add: galery-component
cetav-ddw/proxy-fe pull request #39
Opened 2019-10-29 22:02 UTC by JgeovanniAm

2019-10-29 22:05 UTC, glorianaa80 approved these changes
Code review listo

2019-10-29 22:27 UTC, jleiva requested changes

2019-10-29 22:27 UTC, jleiva commented on src/components/sections/workGalery/index.jsx
> +const workGalery = ({ querySrc }) => {
Gallery es con doble ll

2019-10-29 22:27 UTC, jleiva commented on src/templates/obra.jsx
> +        mainContent={<WorkGalery querySrc={node} />}
porque el prop se llama querySync? que es un querySync? le estas pasando todo el objeto de la obra, pero solo deberias de necesitar la parte de imagenes y video, se puede llamar como mediaData o algo asi

2019-10-29 22:27 UTC, jleiva commented on src/components/sections/workGalery/index.jsx
> +  let srcImage = (querySrc.images.length > 0 && querySrc.images);
- esta condicion esta mal ordenada, si images no existe va a dar un error porque estas tratando de acceder a length de undefined. En el caso de que images si tenga data, a srcImage se le va a asignar el array completo, no el length; en el caso en que images este vacio estas asignandole a srcImage false
- los parentesis no se necesitan
- el nombre srcImage no aplica, porque images es un array de objetos, puede ser uno, vacio o muchos

2019-10-29 22:27 UTC, jleiva commented on src/components/sections/workGalery/index.jsx
> +      <div className="galery__wrapper-img">
el div completo deberia de estar condicionado, si no hay imagenes el div tampoco se deberia de renderear

2019-10-29 22:27 UTC, jleiva commented on src/components/sections/workGalery/index.jsx
> +    <section className="galery">
gallery, es con doble ll

2019-10-29 22:27 UTC, jleiva commented on src/components/sections/workGalery/index.jsx
> +import Image from '../../units/Image';
deberiamos de estar usando el Image de Gatsby, import Img from "gatsby-image", voy a cambiarlo en Obras

el archivo de css deberia de seguir el mismo nombre de la section, como en los otros componentes

2019-10-29 22:43 UTC, JgeovanniAm commented on src/templates/obra.jsx
> +        mainContent={<WorkGalery querySrc={node} />}
ok

2019-10-30 02:14 UTC, jleiva requested changes

2019-10-30 02:14 UTC, jleiva commented on src/templates/obra.jsx
> +        mainContent={<WorkGallery mediaData={{imageArray:node.images, urlVideo: node.video}} />}
urlVideo no suena apropiado, porque no le estas pasando una url, le estas pasando toda la data de video, que hasta donde recuerdo es un objeto que lleva la url y el thumbnail, ademas, estas dejando por fuera cuando el se agrego un file de video a la obra.

2019-10-30 02:14 UTC, jleiva commented on src/components/sections/workGallery/index.jsx
> +        {imageArray.length > 0 ? imageArray.map((item, index) => <Image key={index} variant="gallery__img-art" source={item.url} alt="art" />) : null}
el alt no esta bien, mejor dejalo vacio

mismo comentario de la revision anterior, si no hay imagenes el div no se deberia de renderear

2019-10-30 02:14 UTC, jleiva commented on src/components/sections/workGallery/index.jsx
> +import React, { useState, useEffect } from 'react';
los hooks no se estan usando, y tiran un warning de eslint, borralos porfa

2019-10-30 02:14 UTC, jleiva commented on src/components/sections/workGallery/index.jsx
> +function drawCanvas(canvas) {
habiamos quedado que la animacion no se iba a incluir, que eso lo agregamos hasta al final como un nice to have, porfa eliminalo de este PR.

2019-10-30 02:14 UTC, jleiva commented on src/components/sections/workGallery/styles.scss
> +
este archivo se debe llamar como la seccion, igual que los otros archivos

2019-10-30 04:00 UTC, JgeovanniAm commented on src/templates/obra.jsx
> +        mainContent={<WorkGallery mediaData={{imageArray:node.images, urlVideo: node.video}} />}
ya quito lo del video eso debería ir en otro branch

2019-10-30 04:03 UTC, JgeovanniAm commented on src/components/sections/workGalery/index.jsx
> +import Image from '../../units/Image';
se cambia la que está en units  a gatsby-image? o se elimina ese componente unit ?

2019-10-30 16:01 UTC, jleiva requested changes

2019-10-30 16:01 UTC, jleiva commented on src/components/sections/workGallery/index.jsx
> +        <Button variant="gallery__bnt gallery__bnt--left arrow-left">
porque  los botones tienen dos modificadores?

2019-10-31 05:14 UTC, jleiva approved these changes

2019-10-31 05:16 UTC, merged