update: styles and files .scss
cetav-ddw/proxy-fe pull request #71
Opened 2019-11-03 02:54 UTC by JgeovanniAm

2019-11-03 03:04 UTC, jleiva requested changes

2019-11-03 03:04 UTC, jleiva commented on src/components/sections/modalidades/index.jsx
> +        <h3 className="column-type__title content-title">Pabellon</h3>
aqui tiene que decir: Pabellón/Pavillion

2019-11-03 03:04 UTC, jleiva commented on src/components/sections/nav/index.jsx
> +    document.body.style.overflow = 'visible';
visible es el valor default de overflow, no hace falta declararlo en cada mount

2019-11-03 03:17 UTC, JgeovanniAm commented on src/components/sections/nav/index.jsx
> +    document.body.style.overflow = 'visible';
Cuando hago el click del btn el siempre se va quedar con el hidden o con el visible. Entonces que pasa cuando hago click a un Link? El se va quedar con el hidden. Por eso hice el mount.

2019-11-03 15:23 UTC, NycollSM approved these changes

2019-11-03 18:01 UTC, glorianaa80 approved these changes

2019-11-04 15:06 UTC, jleiva commented on src/components/sections/nav/index.jsx
> +    document.body.style.overflow = 'visible';
suena medio hacky, voy a aprobarlo para tenerlo en develop y que veamos bien el issue

2019-11-04 15:07 UTC, merged